# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d27b4daba1ab7c6622da0b11f1975627d2373f908512a66108e5590834173c3869672212d9db091d1563540d16145993d9f38435813c62ac37b674369ad7b213

test:
  secret_key_base: 9b3485272a8d1dab2d8d1c8747b7d13495cc84103a5015bcc71155a45370b72342380f1a93b221c91771089e6145b9b6740c3f97edec0bd8e83651c432158301

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
